window.__ModuleLoader__.load({id:"dsh-settings-organizer",factory:function(require){
var module={exports:{}},React=require("react"),KEY="dsh-settings-organizer:v2";
var DEFAULT={version:2,showEmpty:false,safeMode:false,assignments:{},nodes:[
{id:"session",label:"会话",children:["对话管理","会话管理","侧边临时会话","状态文案"]},
{id:"workspace",label:"工作区",children:["记忆","快照","文件提及"]},
{id:"security",label:"插件安全",children:["插件管理","插件检测","备份管理"]},
{id:"extensions",label:"界面扩展",children:["通知","扩展管理","侧边卡片","顶部按钮管理"]},
{id:"automation",label:"Agent 与自动化",children:[]},{id:"developer",label:"开发工具",children:[]},{id:"external",label:"外部服务",children:[]},{id:"other",label:"其他扩展",children:[]}]};
function copy(x){return JSON.parse(JSON.stringify(x));} function load(){try{var x=JSON.parse(localStorage.getItem(KEY)||"");return x&&x.version===2?x:copy(DEFAULT);}catch(_){return copy(DEFAULT);}} var state=load();
function save(x){state=x;localStorage.setItem(KEY,JSON.stringify(x));restore();organize();}
var moved=new Map(),timer=0;
function labelOf(x){return(x.textContent||"").replace(/\s+/g," ").trim();}
function defaultGroup(label){for(var i=0;i<state.nodes.length;i++)if(state.nodes[i].children.indexOf(label)>=0)return state.nodes[i].id;return"other";}
function nav(){var target=Array.from(document.querySelectorAll("button,a")).find(function(x){return labelOf(x)==="导航管理";});if(!target)return null;var p=target.parentElement;while(p&&p.querySelectorAll(":scope > button,:scope > a").length<5)p=p.parentElement;return p;}
function restore(){moved.forEach(function(v,row){if(v.parent&&v.parent.isConnected)v.parent.insertBefore(row,v.next&&v.next.isConnected?v.next:null);});moved.clear();document.querySelectorAll(".dsho-nav-group").forEach(function(x){x.remove();});}
function organize(){clearTimeout(timer);timer=setTimeout(function(){if(document.querySelector(".dsho-nav-group"))return;restore();if(state.safeMode)return;var n=nav();if(!n)return;n.classList.add("dsho-organized");var core=["通用设置","模型","插件","Agent 预设","导航管理"],b={};state.nodes.forEach(function(g){b[g.id]=[];});Array.from(n.querySelectorAll(":scope > button,:scope > a")).forEach(function(row){var l=labelOf(row);if(core.indexOf(l)>=0)return;var id=state.assignments[l]||defaultGroup(l);if(b[id])b[id].push(row);});state.nodes.forEach(function(g){var list=b[g.id]||[];if(!list.length&&!state.showEmpty)return;var box=document.createElement("div"),h=document.createElement("button"),body=document.createElement("div");box.className="dsho-nav-group";h.className="dsho-nav-head";h.type="button";h.textContent=g.label;body.className="dsho-nav-items";h.onclick=function(){body.hidden=!body.hidden;};box.append(h,body);n.appendChild(box);list.forEach(function(row){moved.set(row,{parent:n,next:row.nextSibling});body.appendChild(row);});});},50);}
function css(){if(document.getElementById("dsho-css"))return;var s=document.createElement("style");s.id="dsho-css";s.textContent=".dsho-card{max-width:760px;padding:20px}.dsho-tools{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.dsho-btn{border:1px solid var(--ds-border,#d9dde5);background:var(--ds-bg,#fff);border-radius:7px;padding:7px 11px;cursor:pointer}.dsho-primary{background:#2563eb;color:#fff;border-color:#2563eb}.dsho-tree{border:1px solid var(--ds-border,#e3e7ee);border-radius:9px;overflow:hidden}.dsho-row{display:flex;align-items:center;gap:8px;padding:9px 11px;border-bottom:1px solid var(--ds-border,#edf0f4)}.dsho-group{background:var(--ds-bg-secondary,#f7f8fa);font-weight:600}.dsho-child{padding-left:32px}.dsho-label{flex:1}.dsho-actions{display:flex;gap:2px}.dsho-actions button{border:0;background:transparent;padding:4px 6px;cursor:pointer;color:var(--ds-text-secondary,#697386)}.dsho-hint{font-size:13px;color:var(--ds-text-secondary,#697386);line-height:1.5}@media(prefers-reduced-motion:no-preference){.dsho-row{transition:background .14s ease}.dsho-row:hover{background:rgba(37,99,235,.06)}}";document.head.appendChild(s);}
function navCss(){var s=document.createElement("style");s.textContent=".dsho-organized{overflow-y:auto;scrollbar-gutter:stable}.dsho-nav-group{width:100%}.dsho-nav-head{width:100%;border:0;background:transparent;text-align:left;padding:9px 16px;color:#697386;font-size:13px;font-weight:600;cursor:pointer}.dsho-nav-items{display:flex;flex-direction:column}.dsho-nav-items>button,.dsho-nav-items>a{padding-left:28px!important}";document.head.appendChild(s);}
function move(id,d){var a=copy(state);var i=a.nodes.findIndex(function(x){return x.id===id}),j=i+d;if(i>=0&&j>=0&&j<a.nodes.length){var t=a.nodes[i];a.nodes[i]=a.nodes[j];a.nodes[j]=t;save(a);organize();}}
function Editor(){var tick=React.useState(0),refresh=tick[1];function redraw(){refresh(function(x){return x+1;});}function add(){var l=prompt("新分组名称");if(!l)return;var a=copy(state);a.nodes.push({id:"group-"+Date.now(),label:l,children:[]});save(a);redraw();}function rename(n){var l=prompt("分组名称",n.label);if(l){n.label=l;save(state);redraw();}}function reset(){if(confirm("恢复默认分类？")){state=copy(DEFAULT);save(state);redraw();}}function exp(){var a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download="dsh-settings-navigation.json";a.click();}function imp(){var i=document.createElement("input");i.type="file";i.accept="application/json";i.onchange=function(){var f=i.files&&i.files[0];if(!f)return;var r=new FileReader();r.onload=function(){try{var x=JSON.parse(r.result);if(!x.nodes)throw 0;x.version=2;save(x);redraw();}catch(_){alert("配置文件无效");}};r.readAsText(f);};i.click();}function row(n){return React.createElement(React.Fragment,{key:n.id},React.createElement("div",{className:"dsho-row dsho-group"},React.createElement("span",{className:"dsho-label"},n.label),React.createElement("span",{className:"dsho-actions"},React.createElement("button",{title:"上移",onClick:function(){move(n.id,-1);redraw();}},"↑"),React.createElement("button",{title:"下移",onClick:function(){move(n.id,1);redraw();}},"↓"),React.createElement("button",{title:"重命名",onClick:function(){rename(n);}},"改名"))),n.children.map(function(x){return typeof x==="string"?React.createElement("div",{className:"dsho-row dsho-child",key:x},React.createElement("span",{className:"dsho-label"},x)):null;}));}return React.createElement("div",{className:"dsho-card"},React.createElement("h3",null,"设置导航管理"),React.createElement("p",{className:"dsho-hint"},"编辑一级、二级和三级分组。未知页面保留，导航管理始终可见。"),React.createElement("div",{className:"dsho-tools"},React.createElement("button",{className:"dsho-btn dsho-primary",onClick:add},"新建分组"),React.createElement("button",{className:"dsho-btn",onClick:reset},"恢复默认"),React.createElement("button",{className:"dsho-btn",onClick:exp},"导出"),React.createElement("button",{className:"dsho-btn",onClick:imp},"导入"),React.createElement("label",{className:"dsho-hint"},React.createElement("input",{type:"checkbox",checked:state.showEmpty,onChange:function(e){state.showEmpty=e.target.checked;save(state);redraw();}})," 显示空分组"),React.createElement("label",{className:"dsho-hint"},React.createElement("input",{type:"checkbox",checked:state.safeMode,onChange:function(e){state.safeMode=e.target.checked;save(state);redraw();}})," 安全模式")),React.createElement("div",{className:"dsho-tree"},state.nodes.filter(function(n){return state.showEmpty||n.children.length;}).map(row)));}
function apply(ctx){css();navCss();var observer=new MutationObserver(organize);observer.observe(document.body,{childList:true,subtree:true});organize();ctx.effect(function(){return function(){observer.disconnect();restore();};});ctx.slots.inject("settings.section",function(){return ctx.slots.register({name:"settings.section",id:"dsh-settings-organizer",order:150,label:function(){return "导航管理";}},Editor);});}module.exports.apply=apply;module.exports.inject=["slots"];return module.exports;}});
